Repository WildCodeSchool/2023-09-orleans-cda-projet1-groupe-a, pull requests merged in 2023-11, with the labels that each got.

#78 Feature/random picture home
  public/BG1.jpg
  public/BG10.jpg
  public/BG2.jpg
  public/BG3.jpg
  public/BG4.jpg
  public/BG5.jpg
  public/BG6.jpg
  public/BG7.jpg
  public/BG8.jpg
  public/BG9.jpg
  src/pages/Home.jsx
  tailwind.config.js
Labels: Reviewed 😎, Sylvain Let'ssss Go 🫵🏼

#83 fix legal notice
  src/pages/LegalNotice.jsx
Labels: Reviewed 😎, Sylvain Let'ssss Go 🫵🏼

#87 responsive ok
  src/components/ArtistCollection.jsx
  src/main.css
  src/pages/Artworks.jsx
Labels: Reviewed 😎, Sylvain Let'ssss Go 🫵🏼

#80 Feature/fix home zone 1
  src/components/HomeContent1.jsx
  src/components/HomeContent2.jsx
  src/components/HomeContent3.jsx
Labels: Reviewed 😎, Sylvain Let'ssss Go 🫵🏼

#84 a better version of filterBar responsive
  src/components/FilterBar.jsx
Labels: Reviewed 😎, Sylvain Let'ssss Go 🫵🏼

#85 Feature/fix nav
  src/components/HomeContent1.jsx
  src/components/Layout.jsx
  src/components/NavBar.jsx
  src/components/ScrollTopButton.jsx
Labels: Reviewed 😎, Sylvain Let'ssss Go 🫵🏼

#88 just adding some padding
  src/components/Footer.jsx
Labels: Reviewed 😎, Sylvain Let'ssss Go 🫵🏼

#89 just adding some margin
  src/components/FilterBar.jsx
Labels: Reviewed 😎, Sylvain Let'ssss Go 🫵🏼

#91 Feature/index picture
  src/components/ArtistCollection.jsx
Labels: Reviewed 😎, Sylvain Let'ssss Go 🫵🏼

#90 Feature/fix text picture
  src/components/ArtistCollection.jsx
  src/components/FilterBar.jsx
  src/components/HomeContent2.jsx
  src/pages/AllArtists.jsx
  src/pages/Artworks.jsx
  src/pages/Gallery.jsx
Labels: Reviewed 😎, Sylvain Let'ssss Go 🫵🏼

#92 fix-home
  src/components/HomeContent1.jsx
  src/components/HomeContent2.jsx
  src/components/HomeContent3.jsx
Labels: Reviewed 😎, Sylvain Let'ssss Go 🫵🏼

#98 router update
  src/router.jsx
Labels: Reviewed 😎, Sylvain Let'ssss Go 🫵🏼

#95 removing unnecessary assignments
  src/components/NavBar.jsx
Labels: Reviewed 😎, Sylvain Let'ssss Go 🫵🏼

#97 Release/v0.1.0
  index.html
  public/bg-1.jpg
  public/bg-10.jpg
  public/bg-2.jpg
  public/bg-3.jpg
  public/bg-4.jpg
  public/bg-5.jpg
  public/bg-6.jpg
  public/bg-7.jpg
  public/bg-8.jpg
  public/bg-9.jpg
  public/bg.avif
  public/logo.svg
  src/App.css
  src/App.jsx
  src/api.js
  src/assets/images/home-1.png
  src/assets/images/home-2.png
  src/assets/images/home-3.png
  src/assets/images/home-4.png
  src/assets/images/home-5.png
  src/assets/images/home-6.png
  src/assets/images/ja.png
  src/components/ArtistCollection.jsx
  src/components/Footer.jsx
  src/components/HomeContent1.jsx
  src/components/HomeContent2.jsx
  src/components/HomeContent3.jsx
  src/components/NavBar.jsx
  src/data.js
  src/main.css
  src/pages/Artists.jsx
  src/pages/Home.jsx
  tailwind.config.js
Labels: Reviewed 😎, Need Review 👌

#96 Hotfix/navbar useless assignations
  src/components/NavBar.jsx
Labels: Reviewed 😎, Sylvain Let'ssss Go 🫵🏼

#99 Hotfix/router
  src/router.jsx
Labels: Reviewed 😎, Sylvain Let'ssss Go 🫵🏼

#101 Hotfix/fix gh action
  .github/workflows/deploy.yml
Labels: Sylvain Let'ssss Go 🫵🏼

#93 gallery effect
  src/pages/Gallery.jsx
Labels: Reviewed 😎, Sylvain Let'ssss Go 🫵🏼

#102 vite logo removed from images
  public/vite.svg
Labels: Reviewed 😎, Sylvain Let'ssss Go 🫵🏼

#103 vite logo removed from images
  public/vite.svg
Labels: Reviewed 😎, Sylvain Let'ssss Go 🫵🏼

#105 Hotfix/url picture
  src/pages/NotFound.jsx
Labels: Reviewed 😎, Sylvain Let'ssss Go 🫵🏼

#94 Feature/api and picture
  src/api.js
  src/assets/images/home-1.png
  src/assets/images/home-10.jpg
  src/assets/images/home-11.jpg
  src/assets/images/home-2.png
  src/assets/images/home-3.jpg
  src/assets/images/home-4.jpg
  src/assets/images/home-5.jpg
  src/assets/images/home-6.jpg
  src/assets/images/home-9.jpg
  src/assets/images/image-home-l.png
  src/assets/images/image-home-r.png
  src/components/ArtistCollection.jsx
  src/components/HomeContent1.jsx
  src/components/HomeContent2.jsx
  src/components/HomeContent3.jsx
  src/components/SearchInput.jsx
  src/pages/AllArtists.jsx
  src/pages/Artists.jsx
  src/pages/Gallery.jsx
  src/router.jsx
Labels: Reviewed 😎, Sylvain Let'ssss Go 🫵🏼

#104 Feature/fix url picture
  src/pages/NotFound.jsx
Labels: Reviewed 😎, Sylvain Let'ssss Go 🫵🏼

#106 cursor pointer filter
  src/components/FilterBar.jsx
  src/pages/Gallery.jsx
Labels: Reviewed 😎, Sylvain Let'ssss Go 🫵🏼

#110 picture size ok
  src/components/HomeContent2.jsx
Labels: Reviewed 😎, Sylvain Let'ssss Go 🫵🏼

#112 Hotfix/router
  src/router.jsx
Labels: Reviewed 😎, Sylvain Let'ssss Go 🫵🏼
